services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    command: ["alembic", "upgrade", "head"]

  get_data:
    build: .
    env_file:
      - .env
    depends_on:
      - migrate
    command: ["python", "-m", "src.scrapers.wiki_scraper"]

  print_data:
    build: .
    env_file:
      - .env
    depends_on:
      - migrate
    command: ["python", "-m", "src.main"]

volumes:
  postgres_data:
